version = 0.1

[default]
[default.global.parameters]
stack_name = "pdf-lecture-service"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-east-1"
parameter_overrides = "Stage=dev"

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[staging]
[staging.deploy.parameters]
stack_name = "pdf-lecture-service-staging"
parameter_overrides = "Stage=staging"
confirm_changeset = false

[prod]
[prod.deploy.parameters]
stack_name = "pdf-lecture-service-prod"
parameter_overrides = "Stage=prod"
confirm_changeset = true
